### PR TITLE
prettierx: Add tslib to avoid a peerDependencies warning

### PR DESCRIPTION
**Pull request by ai**
Right now Yarn always prints a warning about missed peer dependency for all `prettierx` users.

```
warning "eslint-plugin-prettierx > prettierx > @angular/compiler@9.0.5" has unmet peer dependency "tslib@^1.10.0".
```

This PR will fix this warning.

### CODE REVIEW

**Comment by brody2consult** [comment]
My apologies for the delay. I will likely give this a quick test and include it in the upcoming release (0.15.0). I would like to add a note in the "prettierx dependencies notes" in package.json unless @ai wants to add the note.

**Comment by ai** [comment]
I am bad with writing notes in English

**Comment by brody2consult** [comment]
I will make the note, no worries.

**Comment by brody2consult** [comment]
@ai I just updated the title, pushed some updates, and added a note to package.json. This may not be very good timing but if you want to review the updates and make any other changes I would be grateful. I would like to merge and release by Monday or Tuesday unless there is a very good reason not to.

I am in the process of updating some other dependencies and would very likely regenerate yarn.lock before merging this one.

I found a few minor things to note:

- This would not be needed once `@angular/compiler` is updated to 10 or 11 (Prettier is already using version 11)
- I did test this in my work area. Unfortunately there is another Yarn warning coming from outdated `@typescript-eslint/typescript-estree` which seems to be resolved in version 4, now used by Prettier.
- I am now thinking this can be a patch release, since it is simply adding a not-too-large dependency as a bug fix.

**Comment by ai** [comment]
LGTM

**Pull request merged**
